Algoritmo "EXERCICIO_20"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicita dois números e volta o crescente
// Autor(a)    : Matheus
// Data atual  : 29/03/2023
Var
valor1, valor2: real

Inicio
Escreval("Digite o primeiro valor: ")
Leia(valor1)
Escreval("Digite o segundo valor: ")
Leia(valor2)

se (valor1 > valor2) Entao
Escreval(valor2, " ", valor1)
senao
Escreval(valor1, " ", valor2)
FimSe

FimAlgoritmo