Algoritmo "EXERCICIO_7_G_MANZANO"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/04/2023
Var
   A, B, C, D, resultado1, resultado2, resultado3, resultado4, resultado5:inteiro
   resultado6, resultado7, resultado8, resultado9, resultado10, resultado11, resultado12:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Olá, digite o valor de A: ")
   leia(A)

   escreva("Agora, digite o valor de B: ")
   leia(B)

   escreva("Olá, digite o valor de C: ")
   leia(C)

   escreva("Agora, digite o valor de D: ")
   leia(D)

   resultado1 <- A + B
   resultado2 <- A + C
   resultado3 <- A + D
   resultado4 <- B + C
   resultado5 <- B + D
   resultado6 <- C + D
   resultado7 <- A * B
   resultado8 <- A * C
   resultado9 <- A * D
   resultado10 <- B * C
   resultado11 <- B * D
   resultado12 <- C * D

   escreva("___________________________________________________________________")
   escreval("O valor de A + B agora é: ", resultado1)
   escreva("___________________________________________________________________")
   escreval("O valor de A + C agora é: ", resultado2)
   escreva("___________________________________________________________________")
   escreval("O valor de A + D agora é: ", resultado3)
   escreva("___________________________________________________________________")
   escreval("O valor de B + C agora é: ", resultado4)
   escreva("___________________________________________________________________")
   escreval("O valor de B + D agora é: ", resultado5)
   escreva("___________________________________________________________________")
   escreval("O valor de C + D agora é: ", resultado6)
   escreva("___________________________________________________________________")
   escreval("O valor de A * B agora é: ", resultado7)
   escreva("___________________________________________________________________")
   escreval("O valor de A * C agora é: ", resultado8)
   escreva("___________________________________________________________________")
   escreval("O valor de A * D agora é: ", resultado9)
   escreva("___________________________________________________________________")
   escreval("O valor de B * C agora é: ", resultado10)
   escreva("___________________________________________________________________")
   escreval("O valor de B * D agora é: ", resultado11)
   escreva("___________________________________________________________________")
   escreval("O valor de C * D agora é: ", resultado12)
   escreva("___________________________________________________________________")



Fimalgoritmo